name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          pkg-config \
          libssl-dev \
          zlib1g-dev
    
    - name: Configure CMake
      run: |
        cmake -S . -B build-linux \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_CACHE_TEST=ON \
          -DENABLE_METRICS=ON \
          -DNO_WINFSP=ON \
          -G Ninja
    
    - name: Build
      run: cmake --build build-linux --parallel
    
    - name: Run comprehensive test suite
      run: |
        # Use our Linux test runner script
        chmod +x run_all_tests_linux.sh
        ./run_all_tests_linux.sh
    



